name: wikimeasurements_env
channels:
  - conda-forge
dependencies:  
  - python==3.9.0
  - pip:    
    - wheel==0.37.1
    - jsonnet==0.17.0
    - setuptools==65.3.0
    - spacy==3.4.1
    - en_core_web_md@https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.4.0/en_core_web_md-3.4.0-py3-none-any.whl
    - coreferee==1.3.0
    - dateparser==1.1.1
    - lupa==1.13
    - matplotlib==3.5.3
    - mwparserfromhell==0.6.4
    - nltk==3.7
    - numexpr==2.8.3
    - numpy==1.23.3
    - pandas==1.4.4
    - pytest==7.1.3
    - requests==2.28.1
    - scipy==1.9.1
    - snakemake==7.15.2
    - sparqlwrapper==2.0.0
    - text2num==2.4.0
    - tqdm==4.64.1
    - typing-extensions==4.5.0
    - pulp==2.7.0
    - wikiextractor==3.0.6
    - networkx==2.8.6
    - black
    - -e .